rules:
  unpinned-uses:
    config:
      policies:
        actions/*: ref-pin
        astral-sh/*: ref-pin
        j178/*: ref-pin
        nick-fields/*: ref-pin
        pypa/*: ref-pin
        softprops/*: ref-pin
        sphinx-notes/*: ref-pin
