language: python
script:
  - coverage run --include="chromalog/*" setup.py nosetests --with-doctest --doctest-extension=rst --tests tests,chromalog,doc/source
  - sphinx-build -b doctest -W doc/source doc/build/html
  - sphinx-build -b html -W doc/source doc/build/html
  - coverage report -m --fail-under=100
after_success: coveralls
